// Generated by devimg. Do not edit by hand.
export const DEVIMG_MANIFEST = {
  version: 1,
  generated_at: "unix:1790381916",
  config_hash: "blake3:b4ced2e41bba9bdc717e1468c38f436cd05c0b9c6231b5cf005fa01e5d6323bd",
  sources: [
    {
      source_path: "public/projects/accesstrace-overview.png",
      source_hash: "blake3:c6dba85b21fa92aeb867dbe194b6796f89fb30d22eb480df7007bae0ea0e5cc5",
      source_width: 1280,
      source_height: 1136,
      source_bytes: 198822,
      variants: [
        {
          src: "/images/generated/projects/accesstrace-overview.project-banner.1200.fef13e67565c.jpeg",
          output_path:
            "public/images/generated/projects/accesstrace-overview.project-banner.1200.fef13e67565c.jpeg",
          preset: "project-banner",
          fit: "cover",
          width: 1200,
          height: 630,
          format: "jpeg",
          bytes: 136450,
          hash: "blake3:fef13e67565caec3b2ec2df6cf2089ee0abd9ee7232f9f0eb009ee9a9cf6fe64"
        },
        {
          src: "/images/generated/projects/accesstrace-overview.project-card.640.cbb0f671a2cc.jpeg",
          output_path:
            "public/images/generated/projects/accesstrace-overview.project-card.640.cbb0f671a2cc.jpeg",
          preset: "project-card",
          fit: "cover",
          width: 640,
          height: 360,
          format: "jpeg",
          bytes: 58835,
          hash: "blake3:cbb0f671a2ccf1626208abbabb7135e3fa486168d99f41dc367c691eaee85646"
        }
      ]
    },
    {
      source_path: "public/projects/cli_tools.png",
      source_hash: "blake3:4dffeaec821cadd3486c8585ce13d0fa1729ebf3c449403c9c3814409ff76b47",
      source_width: 1731,
      source_height: 909,
      source_bytes: 1361650,
      variants: [
        {
          src: "/images/generated/projects/cli_tools.project-banner.1200.cafd458c426a.jpeg",
          output_path:
            "public/images/generated/projects/cli_tools.project-banner.1200.cafd458c426a.jpeg",
          preset: "project-banner",
          fit: "contain",
          width: 1200,
          height: 630,
          format: "jpeg",
          bytes: 121517,
          hash: "blake3:cafd458c426aaecb2c7ea39c77aff27da29df6003e6f164841fc8a2d42d1e420"
        },
        {
          src: "/images/generated/projects/cli_tools.project-card.640.5b8292e81375.jpeg",
          output_path:
            "public/images/generated/projects/cli_tools.project-card.640.5b8292e81375.jpeg",
          preset: "project-card",
          fit: "contain",
          width: 640,
          height: 336,
          format: "jpeg",
          bytes: 44295,
          hash: "blake3:5b8292e813754534cb64304685954447980f1aaf4db860fcf7c1f017aaced325"
        }
      ]
    },
    {
      source_path: "public/projects/devimg.png",
      source_hash: "blake3:fa0d5ad122cf7b25913ef3643651b1804e6463f894f689791c95540318144be4",
      source_width: 1731,
      source_height: 909,
      source_bytes: 1627787,
      variants: [
        {
          src: "/images/generated/projects/devimg.project-banner.1200.4bffb451e10d.jpeg",
          output_path:
            "public/images/generated/projects/devimg.project-banner.1200.4bffb451e10d.jpeg",
          preset: "project-banner",
          fit: "contain",
          width: 1200,
          height: 630,
          format: "jpeg",
          bytes: 195673,
          hash: "blake3:4bffb451e10d67db44ac7a1cd5bbb2e2cd74906a74c118b831d40bd03b5a0b71"
        },
        {
          src: "/images/generated/projects/devimg.project-card.640.1a31a13c61b7.jpeg",
          output_path: "public/images/generated/projects/devimg.project-card.640.1a31a13c61b7.jpeg",
          preset: "project-card",
          fit: "contain",
          width: 640,
          height: 336,
          format: "jpeg",
          bytes: 68327,
          hash: "blake3:1a31a13c61b7be9e47703d8b46a23ece7dc7b1ff629c421b2e5e3f62afb93a2a"
        }
      ]
    },
    {
      source_path: "public/projects/hercilia-catalog.png",
      source_hash: "blake3:9054cc4878d406387447a4f2537f5d1958c3356bcf7efc190906a2f6f4915559",
      source_width: 1440,
      source_height: 900,
      source_bytes: 120101,
      variants: [
        {
          src: "/images/generated/projects/hercilia-catalog.project-banner.1200.779432a27360.jpeg",
          output_path:
            "public/images/generated/projects/hercilia-catalog.project-banner.1200.779432a27360.jpeg",
          preset: "project-banner",
          fit: "contain",
          width: 1008,
          height: 630,
          format: "jpeg",
          bytes: 104673,
          hash: "blake3:779432a2736059e1f1fd12942e7789a6932020c5372a0d97d46a8953199e7281"
        },
        {
          src: "/images/generated/projects/hercilia-catalog.project-card.640.653697641f87.jpeg",
          output_path:
            "public/images/generated/projects/hercilia-catalog.project-card.640.653697641f87.jpeg",
          preset: "project-card",
          fit: "contain",
          width: 576,
          height: 360,
          format: "jpeg",
          bytes: 40415,
          hash: "blake3:653697641f87628ed48ee12f1ecf12a1b369b3e4d14e1c7081ab5cd9cf738fe0"
        }
      ]
    },
    {
      source_path: "public/projects/hercilia-construcoes.png",
      source_hash: "blake3:61c431826e430d08e22aa4cbe4e87f8e277b6dd35cd2e3d79529b6c2d6020b84",
      source_width: 1440,
      source_height: 720,
      source_bytes: 282102,
      variants: [
        {
          src: "/images/generated/projects/hercilia-construcoes.project-banner.1200.e250a0e3408a.jpeg",
          output_path:
            "public/images/generated/projects/hercilia-construcoes.project-banner.1200.e250a0e3408a.jpeg",
          preset: "project-banner",
          fit: "cover",
          width: 1200,
          height: 630,
          format: "jpeg",
          bytes: 136262,
          hash: "blake3:e250a0e3408ab2d1a856fb349023d3dd25d75e9a52fdb6d1797b42b0f2e69520"
        },
        {
          src: "/images/generated/projects/hercilia-construcoes.project-card.640.72d6a2da3c1f.jpeg",
          output_path:
            "public/images/generated/projects/hercilia-construcoes.project-card.640.72d6a2da3c1f.jpeg",
          preset: "project-card",
          fit: "cover",
          width: 640,
          height: 360,
          format: "jpeg",
          bytes: 59641,
          hash: "blake3:72d6a2da3c1f136261e44fa5df0ec5a8c28c04200030c842260a501e7edc4e95"
        }
      ]
    },
    {
      source_path: "public/projects/jira-toggl-quickstart.png",
      source_hash: "blake3:26f6ad88586c1dcdd3aecdda5401dd1c4946c605783396501f9d7f402ceb6449",
      source_width: 2796,
      source_height: 1648,
      source_bytes: 683070,
      variants: [
        {
          src: "/images/generated/projects/jira-toggl-quickstart.project-banner.1200.37170b15baab.jpeg",
          output_path:
            "public/images/generated/projects/jira-toggl-quickstart.project-banner.1200.37170b15baab.jpeg",
          preset: "project-banner",
          fit: "cover",
          width: 1200,
          height: 630,
          format: "jpeg",
          bytes: 111399,
          hash: "blake3:37170b15baab614351fa0bdd7063dd15b3b62d24ff43a394424ed4c0ace075cd"
        },
        {
          src: "/images/generated/projects/jira-toggl-quickstart.project-card.640.e3efb5f1a9b8.jpeg",
          output_path:
            "public/images/generated/projects/jira-toggl-quickstart.project-card.640.e3efb5f1a9b8.jpeg",
          preset: "project-card",
          fit: "cover",
          width: 640,
          height: 360,
          format: "jpeg",
          bytes: 41568,
          hash: "blake3:e3efb5f1a9b8c9c2e0b66534383eaa36eb0052f95402f668da68dedcf430f162"
        }
      ]
    },
    {
      source_path: "public/projects/website.webp",
      source_hash: "blake3:afa14f6f21d5d2bb7a5660eee7005ce244ef8be052ed19ebb40d8bb9e3291fa6",
      source_width: 2796,
      source_height: 1584,
      source_bytes: 108584,
      variants: [
        {
          src: "/images/generated/projects/website.project-banner.1200.8fb712153b69.jpeg",
          output_path:
            "public/images/generated/projects/website.project-banner.1200.8fb712153b69.jpeg",
          preset: "project-banner",
          fit: "cover",
          width: 1200,
          height: 630,
          format: "jpeg",
          bytes: 96980,
          hash: "blake3:8fb712153b69538eb5f815b506bdcf9c76349cc74bd77d57ba05e35d4f13cc01"
        },
        {
          src: "/images/generated/projects/website.project-card.640.4702e7ceb58e.jpeg",
          output_path:
            "public/images/generated/projects/website.project-card.640.4702e7ceb58e.jpeg",
          preset: "project-card",
          fit: "cover",
          width: 640,
          height: 360,
          format: "jpeg",
          bytes: 38785,
          hash: "blake3:4702e7ceb58eabfbcc15cca9adf812892320d5d914927fc29e3fc31f1d599cd6"
        }
      ]
    }
  ]
} as const
