// Generated by devimg. Do not edit by hand.
export const DEVIMG_MANIFEST = {
  version: 1,
  generated_at: "unix:1781148594",
  config_hash: "blake3:7ea1e83f949cd3c6f51f2c7afc177a343c4aa15dc17b1f3b035c9765bda78f7f",
  sources: [
    {
      source_path: "public/images/blog/implementation-planning-vs-desarrollo.es-ES.png",
      source_hash: "blake3:61ba840e45285bcd651acafb3035a5beb4e42257d433661b70d6316603ce8d8c",
      source_width: 1669,
      source_height: 1044,
      source_bytes: 145673,
      variants: [
        {
          src: "/images/generated/blog/implementation-planning-vs-desarrollo.es-ES.blog-card.640.ebc9eec4d192.jpeg",
          output_path:
            "public/images/generated/blog/implementation-planning-vs-desarrollo.es-ES.blog-card.640.ebc9eec4d192.jpeg",
          preset: "blog-card",
          fit: "contain",
          width: 639,
          height: 400,
          format: "jpeg",
          bytes: 52631,
          hash: "blake3:ebc9eec4d192c1a4a66dc13ca73bbc3644085e2d3e6fea4ab3d3d7e9e8b5bd40"
        },
        {
          src: "/images/generated/blog/implementation-planning-vs-desarrollo.es-ES.blog-social.1200.501ac4e62bcf.jpeg",
          output_path:
            "public/images/generated/blog/implementation-planning-vs-desarrollo.es-ES.blog-social.1200.501ac4e62bcf.jpeg",
          preset: "blog-social",
          fit: "contain",
          width: 1200,
          height: 751,
          format: "jpeg",
          bytes: 145071,
          hash: "blake3:501ac4e62bcfc9c6684d439984954cd85ac1c98a7fc8781de62a39d7a7d738e9"
        }
      ]
    },
    {
      source_path: "public/images/blog/implementation-planning-vs-desenvolvimento.pt-BR.png",
      source_hash: "blake3:13f42796f2527a38e55143dfcdc785be5d6bd612b4912abd04dae686a004dfa2",
      source_width: 1665,
      source_height: 1045,
      source_bytes: 151976,
      variants: [
        {
          src: "/images/generated/blog/implementation-planning-vs-desenvolvimento.pt-BR.blog-card.640.451965fa3dd6.jpeg",
          output_path:
            "public/images/generated/blog/implementation-planning-vs-desenvolvimento.pt-BR.blog-card.640.451965fa3dd6.jpeg",
          preset: "blog-card",
          fit: "contain",
          width: 640,
          height: 402,
          format: "jpeg",
          bytes: 57326,
          hash: "blake3:451965fa3dd62b7928751df531390b062f6b072adbb2d3471ba036063778eb20"
        },
        {
          src: "/images/generated/blog/implementation-planning-vs-desenvolvimento.pt-BR.blog-social.1200.afb4ca37872c.jpeg",
          output_path:
            "public/images/generated/blog/implementation-planning-vs-desenvolvimento.pt-BR.blog-social.1200.afb4ca37872c.jpeg",
          preset: "blog-social",
          fit: "contain",
          width: 1200,
          height: 753,
          format: "jpeg",
          bytes: 143012,
          hash: "blake3:afb4ca37872cd63348047d16808560556d15fb36d160bb3baaa42663ea530139"
        }
      ]
    },
    {
      source_path: "public/images/blog/implementation-planning-vs-developing.en-US.png",
      source_hash: "blake3:d44107cc74f50754c71993ed6ee4d0127d2d1d9a89cbfc34eb2bff0ac29d696a",
      source_width: 1663,
      source_height: 1044,
      source_bytes: 132944,
      variants: [
        {
          src: "/images/generated/blog/implementation-planning-vs-developing.en-US.blog-card.640.e1cfe1a91ee9.jpeg",
          output_path:
            "public/images/generated/blog/implementation-planning-vs-developing.en-US.blog-card.640.e1cfe1a91ee9.jpeg",
          preset: "blog-card",
          fit: "contain",
          width: 640,
          height: 402,
          format: "jpeg",
          bytes: 53951,
          hash: "blake3:e1cfe1a91ee9e17f31f05785b761f318b2525340b183786cca394f7681ea3a4e"
        },
        {
          src: "/images/generated/blog/implementation-planning-vs-developing.en-US.blog-social.1200.a289060b857e.jpeg",
          output_path:
            "public/images/generated/blog/implementation-planning-vs-developing.en-US.blog-social.1200.a289060b857e.jpeg",
          preset: "blog-social",
          fit: "contain",
          width: 1199,
          height: 753,
          format: "jpeg",
          bytes: 132719,
          hash: "blake3:a289060b857e2807ee5ba91e5851eca3c311edbb8a2fce1dd24cac1881d58905"
        }
      ]
    }
  ]
} as const
